# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
categories = ["antiques",
   "appliances",
   "arts & crafts",
   "atvs, utvs, snowmobiles",
   "auto parts",
   "aviation",
   "baby & kid stuff",
   "health and beauty",
   "bicycle parts",
   "bicycles",
   "boat parts & accessories",
   "boats",
   "books & magazines",
   "business",
   "cars & trucks",
   "cds / dvds / vhs",
   "cell phones",
   "clothing & accessories",
   "collectibles",
   "computer parts",
   "computers",
   "electronics",
   "farm & garden",
   "furniture",
   "general for sale",
   "heavy equipment",
   "household items",
   "jewelry",
   "materials",
   "motorcycle parts & accessories",
   "motorcycles/scooters",
   "musical instruments",
   "photo/video",
   "recreational vehicles",
   "sporting goods",
   "tickets",
   "tools",
   "toys & games",
   "trailers",
   "video gaming",
   "auto wheels & tires"]